apiVersion: apps/v1
kind: Deployment
metadata:
  name: tecno-verse
  labels:
    app: tecno-verse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tecno-verse
  template:
    metadata:
      labels:
        app: tecno-verse
    spec:
      containers:
        - name: tecno-verse
          image: 312424209605.dkr.ecr.us-east-1.amazonaws.com/tecno-verse:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080